#!/bin/bash

cat > docs/event-lifecycle.md <<'DOC'
# Event Lifecycle

## Event types

| Event        | Generated by          | Meaning                                              |
|--------------|-----------------------|------------------------------------------------------|
| `submitted`  | Intake                | Request received and normalized                      |
| `reviewed`   | Governance            | Request analyzed and reviewed                        |
| `approved`   | Governance Authority  | Request explicitly approved                          |
| `validated`  | Validation            | Governance chain verified against structural rules   |
| `rejected`   | Governance/Validation | Request or decision rejected                         |
| `executed`   | Execution             | Approved and validated decision executed             |
| `correction` | Any authorized role   | Correction recorded as new event                     |

---

## Valid transitions

\`\`\`
submitted
   ↓
reviewed
   ↓
approved
   ↓
validated
   ↓
executed
\`\`\`

Alternative branches:

\`\`\`
reviewed  ──→ rejected
approved  ──→ rejected
validated ──→ rejected
\`\`\`

---

## Constitutional invariant

Execution requires:

\`\`\`
submission
→ governance review
→ explicit approval
→ structural validation
→ execution
\`\`\`

No execution is legitimate without a complete prior governance chain.

---

## Governance separation

| Layer | Responsibility |
|---|---|
| reviewed | analysis |
| approved | authority decision |
| validated | constitutional validation |
| executed | operational execution |

---

## Replay principle

System legitimacy is verified through deterministic replay of the append-only ledger.

State is derived from events, never mutated directly.

DOC

echo ""
echo "===== DOC UPDATED ====="

cat docs/event-lifecycle.md

